using System.Text.Json;

namespace Azure.DevOps.Sdk.Generator;

/// <summary>The result of emitting one area's request builders.</summary>
internal sealed record BuilderEmitResult(string AreaName, string RootBuilderClass, string Code);

/// <summary>
/// Builds the request-builder trie for an area and emits the fluent builder classes,
/// their indexers, operation methods, and typed query-parameter classes.
/// </summary>
internal sealed class BuilderEmitter
{
    private static readonly HashSet<string> ContextSegments = new(StringComparer.Ordinal)
    {
        "{organization}", "{project}", "{team}", "_apis",
    };

    private readonly AreaModel _area;
    private readonly TypeContext _types;
    private readonly HashSet<string> _areaTypeNames = new(StringComparer.Ordinal);
    private readonly List<string> _queryClasses = new();

    public BuilderEmitter(AreaModel area, TypeContext types)
    {
        _area = area;
        _types = types;
    }

    public BuilderEmitResult Emit()
    {
        var root = BuildTrie();
        SpliceWrapperRoots(root);

        var rootClass = NameUtil.Unique($"{_area.AreaName}RequestBuilder", _areaTypeNames);
        root.BuilderClassName = rootClass;
        AssignNames(root, string.Empty);

        var writer = new CodeWriter();
        writer.Line("// <auto-generated />");
        writer.Line("#nullable enable");
        writer.Line("using System;");
        writer.Line("using System.Collections.Generic;");
        writer.Line("using System.IO;");
        writer.Line("using System.Net.Http;");
        writer.Line("using System.Threading;");
        writer.Line("using System.Threading.Tasks;");
        writer.Line("using Azure.DevOps.Sdk;");
        writer.Line("using Azure.DevOps.Sdk.Http;");
        writer.Line("using Azure.DevOps.Sdk.Models;");
        writer.Line($"using Azure.DevOps.Sdk.{_area.AreaName}.Models;");
        writer.Line();
        writer.Open($"namespace Azure.DevOps.Sdk.{_area.AreaName}");

        EmitNode(writer, root);

        foreach (var queryClass in _queryClasses)
        {
            writer.Line(queryClass);
        }

        writer.Close();
        return new BuilderEmitResult(_area.AreaName, rootClass, writer.ToString());
    }

    // ---- Trie construction -------------------------------------------------

    private TrieNode BuildTrie()
    {
        var root = new TrieNode();
        foreach (var op in _area.Operations)
        {
            var segments = SplitResourcePath(op.RawPath);
            var current = root;
            foreach (var segment in segments)
            {
                if (IsParamSegment(segment))
                {
                    var paramName = ExtractParamName(segment);
                    current.ParamChild ??= new TrieNode { IsParam = true };
                    current = current.ParamChild;
                    current.AddParamName(paramName);
                    RecordParamType(current, op, paramName);
                }
                else
                {
                    var key = segment.ToLowerInvariant();
                    if (!current.LiteralChildren.TryGetValue(key, out var child))
                    {
                        child = new TrieNode { CanonicalSegment = segment };
                        current.LiteralChildren[key] = child;
                    }
                    else if (CountUpper(segment) > CountUpper(child.CanonicalSegment))
                    {
                        child.CanonicalSegment = segment; // prefer the camelCase spelling
                    }

                    current = child;
                }
            }

            current.Operations.Add(op);
        }

        return root;
    }

    private void RecordParamType(TrieNode node, SpecOperation op, string paramName)
    {
        var param = op.Parameters.FirstOrDefault(p => p.In == "path" &&
            string.Equals(p.Name, paramName, StringComparison.OrdinalIgnoreCase));
        if (param is null)
        {
            return;
        }

        var mapped = _types.MapType(param.Schema);
        node.ParamTypeCandidates.Add(mapped is "int" or "long" or "Guid" or "string" ? mapped : "string");
    }

    private static void SpliceWrapperRoots(TrieNode root)
    {
        foreach (var child in root.LiteralChildren.Values.ToList())
        {
            if (child.Operations.Count != 0 || child.IsParam)
            {
                continue;
            }

            // Only splice when it introduces no naming collisions at the root.
            var collides = child.LiteralChildren.Keys.Any(root.LiteralChildren.ContainsKey)
                || (child.ParamChild is not null && root.ParamChild is not null);
            if (collides)
            {
                continue;
            }

            foreach (var grandChild in child.LiteralChildren)
            {
                root.LiteralChildren[grandChild.Key] = grandChild.Value;
            }

            if (child.ParamChild is not null)
            {
                root.ParamChild = child.ParamChild;
            }

            root.LiteralChildren.Remove(child.CanonicalSegment.ToLowerInvariant());
        }
    }

    private void AssignNames(TrieNode node, string pathName)
    {
        foreach (var child in node.LiteralChildren.Values)
        {
            var childPath = pathName + NameUtil.Pascal(child.CanonicalSegment);
            child.BuilderClassName = NameUtil.Unique($"{childPath}RequestBuilder", _areaTypeNames);
            AssignNames(child, childPath);
        }

        if (node.ParamChild is not null)
        {
            var childPath = pathName + "Item";
            node.ParamChild.BuilderClassName = NameUtil.Unique($"{childPath}RequestBuilder", _areaTypeNames);
            AssignNames(node.ParamChild, childPath);
        }
    }

    // ---- Emission ----------------------------------------------------------

    private void EmitNode(CodeWriter writer, TrieNode node)
    {
        writer.Open($"public class {node.BuilderClassName} : BaseRequestBuilder");

        writer.Line($"public {node.BuilderClassName}(IRequestAdapter adapter, IReadOnlyDictionary<string, object?> pathParameters)");
        writer.Line("    : base(adapter, pathParameters)");
        writer.Line("{");
        writer.Line("}");
        writer.Line();

        var members = new HashSet<string>(StringComparer.Ordinal)
        {
            node.BuilderClassName, "Adapter", "PathParameters", "AppendPathParameter", "CreateRequest", "Equals", "GetHashCode", "GetType", "ToString",
        };

        // Child accessor properties.
        foreach (var child in node.LiteralChildren.Values.OrderBy(c => c.CanonicalSegment, StringComparer.Ordinal))
        {
            var propName = NameUtil.Unique(NameUtil.Pascal(child.CanonicalSegment), members);
            writer.Doc($"The <c>{child.CanonicalSegment}</c> resource.");
            writer.Line($"public {child.BuilderClassName} {propName} => new {child.BuilderClassName}(Adapter, PathParameters);");
            writer.Line();
        }

        // Indexer for the parameter child.
        if (node.ParamChild is { } paramChild)
        {
            var paramName = paramChild.ParamName!;
            var paramType = paramChild.ParamTypeCandidates.Contains("string") || paramChild.ParamTypeCandidates.Count == 0
                ? "string"
                : paramChild.ParamTypeCandidates.First();
            var paramVar = NameUtil.Escape(NameUtil.Camel(paramName));
            writer.Doc($"Selects a specific item by its <c>{paramName}</c>.");
            writer.Open($"public {paramChild.BuilderClassName} this[{paramType} {paramVar}]");
            writer.Open("get");
            writer.Line($"var pathParameters = AppendPathParameter(\"{Escape(paramName)}\", {paramVar});");
            foreach (var alias in paramChild.ParamNames.Skip(1))
            {
                writer.Line($"pathParameters[\"{Escape(alias)}\"] = {paramVar};");
            }

            writer.Line($"return new {paramChild.BuilderClassName}(Adapter, pathParameters);");
            writer.Close();
            writer.Close();
            writer.Line();
        }

        // Operation methods.
        foreach (var op in node.Operations.OrderBy(o => o.MethodPart, StringComparer.Ordinal))
        {
            EmitMethod(writer, node, op, members);
        }

        writer.Close();
        writer.Line();

        foreach (var child in node.LiteralChildren.Values)
        {
            EmitNode(writer, child);
        }

        if (node.ParamChild is not null)
        {
            EmitNode(writer, node.ParamChild);
        }
    }

    private void EmitMethod(CodeWriter writer, TrieNode node, SpecOperation op, HashSet<string> members)
    {
        var baseName = NameUtil.Pascal(op.MethodPart);
        if (baseName.Length == 0)
        {
            baseName = NameUtil.Pascal(op.HttpMethod);
        }

        var methodName = NameUtil.Unique(baseName + "Async", members);

        var queryParams = op.Parameters.Where(p => p.In == "query").ToList();
        var bodyParam = op.Parameters.FirstOrDefault(p => p.In == "body");

        // Determine the response shape.
        var (callKind, returnType, callExpression) = ResolveReturn(op);

        // Query-parameter type.
        string? queryClassName = null;
        if (queryParams.Count > 0)
        {
            queryClassName = NameUtil.Unique($"{node.BuilderClassName}{baseName}QueryParameters", _areaTypeNames);
            EmitQueryClass(queryClassName, queryParams);
        }

        var configType = queryClassName is not null
            ? $"RequestConfiguration<{queryClassName}>"
            : "RequestConfiguration";

        // Method signature parameters.
        var signature = new List<string>();
        var isStreamBody = bodyParam is not null && op.Consumes.Any(c => c.Contains("octet-stream"));
        string? bodyType = null;
        if (bodyParam is not null)
        {
            bodyType = isStreamBody ? "Stream" : _types.MapType(bodyParam.Schema);
            signature.Add(bodyParam.Required ? $"{bodyType} body" : $"{bodyType}? body = null");
        }

        signature.Add($"Action<{configType}>? requestConfiguration = null");
        signature.Add("CancellationToken cancellationToken = default");

        writer.Doc(op.Description ?? op.OperationId);
        writer.Open($"public async {returnType} {methodName}({string.Join(", ", signature)})");

        var httpMethodExpr = HttpMethodExpression(op.HttpMethod);
        writer.Line($"var requestInfo = CreateRequest({httpMethodExpr}, \"{Escape(op.Host)}\", \"{Escape(op.RawPath)}\");");
        writer.Line($"requestInfo.QueryParameters[\"api-version\"] = \"{Escape(op.ApiVersion)}\";");

        writer.Line($"var requestConfig = new {configType}();");
        writer.Line("requestConfiguration?.Invoke(requestConfig);");
        writer.Line("foreach (var header in requestConfig.Headers) { requestInfo.Headers[header.Key] = header.Value; }");
        writer.Line("if (requestConfig.ApiVersion is not null) { requestInfo.QueryParameters[\"api-version\"] = requestConfig.ApiVersion; }");
        if (queryClassName is not null)
        {
            writer.Line("requestConfig.QueryParameters.Apply(requestInfo.QueryParameters);");
        }

        if (bodyParam is not null)
        {
            if (isStreamBody)
            {
                writer.Line("var streamContent = new StreamContent(body);");
                writer.Line("streamContent.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue(\"application/octet-stream\");");
                writer.Line("requestInfo.RawContent = streamContent;");
            }
            else
            {
                var contentType = bodyType == "global::Azure.DevOps.Sdk.Models.JsonPatchDocument"
                    ? "global::Azure.DevOps.Sdk.Models.JsonPatchDocument.ContentType"
                    : "\"application/json\"";
                writer.Line("requestInfo.Content = body;");
                writer.Line($"requestInfo.ContentType = {contentType};");
            }
        }

        if (callKind == CallKind.Stream)
        {
            writer.Line("requestInfo.Accept = \"application/octet-stream\";");
        }

        if (callKind == CallKind.NoContent)
        {
            writer.Line($"await {callExpression};");
        }
        else
        {
            writer.Line($"return await {callExpression};");
        }
        writer.Close();
        writer.Line();
    }

    private enum CallKind { Single, Collection, Stream, NoContent }

    private static readonly (CallKind, string, string) StreamReturn =
        (CallKind.Stream, "Task<Stream>", "Adapter.SendStreamAsync(requestInfo, cancellationToken).ConfigureAwait(false)");

    private (CallKind Kind, string ReturnType, string Call) ResolveReturn(SpecOperation op)
    {
        // A binary 'produces' list (octet-stream/zip/...) only forces a Stream when there is no
        // usable JSON schema. Azure DevOps returns JSON by default for these endpoints; the binary
        // form is opt-in, so a concrete object/array schema must win over the binary hint.
        var isBinary = op.Produces.Any(p =>
            p.Contains("octet-stream") || p.Contains("zip") || p.Contains("pdf") || p.Contains("gzip"));

        if (op.SuccessSchema is { } schema)
        {
            var type = schema.TryGetProperty("type", out var t) ? t.GetString() : null;
            var format = schema.TryGetProperty("format", out var f) ? f.GetString() : null;

            if (type == "array")
            {
                var itemType = schema.TryGetProperty("items", out var items) ? _types.MapType(items) : "object";
                return (CallKind.Collection,
                    $"Task<PagedList<{itemType}>>",
                    $"Adapter.SendCollectionAsync<{itemType}>(requestInfo, cancellationToken).ConfigureAwait(false)");
            }

            if (IsConcreteJsonSchema(schema, type, format))
            {
                var single = _types.MapType(schema);
                return (CallKind.Single,
                    $"Task<{single}?>",
                    $"Adapter.SendAsync<{single}>(requestInfo, cancellationToken).ConfigureAwait(false)");
            }

            // Non-concrete schema (file, binary string, or bare object placeholder).
            if (type == "file" || IsBinaryFormat(format) || isBinary)
            {
                return StreamReturn;
            }

            var fallback = _types.MapType(schema);
            return (CallKind.Single,
                $"Task<{fallback}?>",
                $"Adapter.SendAsync<{fallback}>(requestInfo, cancellationToken).ConfigureAwait(false)");
        }

        return isBinary
            ? StreamReturn
            : (CallKind.NoContent, "Task", "Adapter.SendNoContentAsync(requestInfo, cancellationToken).ConfigureAwait(false)");
    }

    private static bool IsConcreteJsonSchema(JsonElement schema, string? type, string? format)
    {
        if (schema.TryGetProperty("$ref", out _) || schema.TryGetProperty("allOf", out _))
        {
            return true;
        }

        return type switch
        {
            "integer" or "number" or "boolean" => true,
            "string" => !IsBinaryFormat(format),
            "object" => schema.TryGetProperty("properties", out var p) && p.ValueKind == JsonValueKind.Object && p.EnumerateObject().Any(),
            _ => false,
        };
    }

    private static bool IsBinaryFormat(string? format) =>
        format is not null &&
        (format.Equals("binary", StringComparison.OrdinalIgnoreCase)
            || format.Equals("byte", StringComparison.OrdinalIgnoreCase)
            || format.Equals("stream", StringComparison.OrdinalIgnoreCase));

    private void EmitQueryClass(string className, List<SpecParameter> queryParams)
    {
        var writer = new CodeWriter();
        writer.Doc("Query parameters for the operation.");
        writer.Open($"public sealed class {className}");

        var taken = new HashSet<string>(StringComparer.Ordinal) { className, "Apply" };
        var entries = new List<(string Prop, string Key)>();
        foreach (var param in queryParams)
        {
            var type = _types.MapType(param.Schema);
            var propName = NameUtil.Unique(NameUtil.Pascal(param.Name), taken);
            entries.Add((propName, param.Name));

            writer.Doc(param.Description);
            writer.Line($"public {type}? {propName} {{ get; set; }}");
            writer.Line();
        }

        writer.Open("internal void Apply(IDictionary<string, object?> query)");
        foreach (var (prop, key) in entries)
        {
            writer.Line($"if ({prop} is not null) {{ query[\"{Escape(key)}\"] = {prop}; }}");
        }

        writer.Close();
        writer.Close();
        _queryClasses.Add(writer.ToString());
    }

    // ---- Helpers -----------------------------------------------------------

    private static List<string> SplitResourcePath(string path) =>
        path.Split('/', StringSplitOptions.RemoveEmptyEntries)
            .Where(s => !ContextSegments.Contains(s))
            .ToList();

    private static bool IsParamSegment(string segment) => segment.Contains('{');

    private static string ExtractParamName(string segment)
    {
        var open = segment.IndexOf('{');
        var close = segment.IndexOf('}');
        return close > open ? segment[(open + 1)..close] : segment.Trim('{', '}', '$', '@');
    }

    private static int CountUpper(string text) => text.Count(char.IsUpper);

    private static string HttpMethodExpression(string method) => method switch
    {
        "GET" => "HttpMethod.Get",
        "POST" => "HttpMethod.Post",
        "PUT" => "HttpMethod.Put",
        "DELETE" => "HttpMethod.Delete",
        "PATCH" => "HttpMethod.Patch",
        "HEAD" => "HttpMethod.Head",
        _ => $"new HttpMethod(\"{method}\")",
    };

    private static string Escape(string text) => text.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
