using System.Text.Json;

namespace Azure.DevOps.Sdk.Generator;

/// <summary>Emits the model classes and enums for one area into a single source file.</summary>
internal sealed class ModelEmitter
{
    private readonly AreaModel _area;
    private readonly TypeContext _types;

    public ModelEmitter(AreaModel area, TypeContext types)
    {
        _area = area;
        _types = types;
    }

    public string Emit()
    {
        var writer = new CodeWriter();
        writer.Line("// <auto-generated />");
        writer.Line("#nullable enable");
        writer.Line("using System;");
        writer.Line("using System.Collections.Generic;");
        writer.Line("using System.Text.Json.Serialization;");
        writer.Line();
        writer.Open($"namespace Azure.DevOps.Sdk.{_area.AreaName}.Models");

        foreach (var enumDef in _types.Enums.Values.OrderBy(e => e.CSharpName, StringComparer.Ordinal))
        {
            EmitEnum(writer, enumDef);
        }

        foreach (var def in _area.Definitions.OrderBy(d => d.Key, StringComparer.Ordinal))
        {
            if (!_types.ClassNames.TryGetValue(def.Key, out var className))
            {
                continue; // skipped (enum schema or shared JSON Patch type)
            }

            EmitClass(writer, className, def.Value);
        }

        writer.Close();
        return writer.ToString();
    }

    private static void EmitEnum(CodeWriter writer, EnumDef def)
    {
        if (def.IsFlags)
        {
            writer.Line("[Flags]");
        }

        writer.Open($"public enum {def.CSharpName}");
        var bit = 1L;
        foreach (var (wire, identifier, description) in def.Members)
        {
            writer.Doc(description);
            writer.Line($"[JsonStringEnumMemberName(\"{Escape(wire)}\")]");
            if (def.IsFlags)
            {
                writer.Line($"{identifier} = {bit},");
                bit <<= 1;
            }
            else
            {
                writer.Line($"{identifier},");
            }
        }

        writer.Close();
        writer.Line();
    }

    private void EmitClass(CodeWriter writer, string className, JsonElement schema)
    {
        var properties = new List<(string Json, JsonElement Schema)>();
        string? baseName = null;

        // Dictionary-shaped definition: object with additionalProperties and no declared properties.
        if (IsDictionaryClass(schema, out var valueType))
        {
            writer.Doc(GetDescription(schema));
            writer.Line($"public class {className} : Dictionary<string, {valueType}>");
            writer.Line("{");
            writer.Line("}");
            writer.Line();
            return;
        }

        CollectProperties(schema, properties, ref baseName);

        var baseClause = baseName is not null ? $" : {baseName}" : string.Empty;
        writer.Doc(GetDescription(schema));
        writer.Open($"public class {className}{baseClause}");

        var taken = new HashSet<string>(StringComparer.Ordinal) { className };
        foreach (var (json, propSchema) in properties)
        {
            var type = _types.MapType(propSchema);
            var propName = NameUtil.Unique(NameUtil.Pascal(json), taken);
            var description = propSchema.TryGetProperty("description", out var d) ? d.GetString() : null;

            writer.Doc(description);
            writer.Line($"[JsonPropertyName(\"{Escape(json)}\")]");
            writer.Line($"public {type}? {propName} {{ get; set; }}");
            writer.Line();
        }

        writer.Close();
        writer.Line();
    }

    private void CollectProperties(JsonElement schema, List<(string, JsonElement)> properties, ref string? baseName)
    {
        if (schema.TryGetProperty("allOf", out var allOf) && allOf.ValueKind == JsonValueKind.Array)
        {
            foreach (var entry in allOf.EnumerateArray())
            {
                if (entry.TryGetProperty("$ref", out var refEl))
                {
                    var resolved = ResolveBase(refEl.GetString());
                    if (resolved is not null)
                    {
                        baseName ??= resolved;
                    }
                }
                else if (entry.TryGetProperty("properties", out var inlineProps))
                {
                    AddProperties(inlineProps, properties);
                }
            }
        }

        if (schema.TryGetProperty("properties", out var ownProps))
        {
            AddProperties(ownProps, properties);
        }
    }

    private static void AddProperties(JsonElement props, List<(string, JsonElement)> properties)
    {
        if (props.ValueKind != JsonValueKind.Object)
        {
            return;
        }

        var seen = new HashSet<string>(properties.Select(p => p.Item1), StringComparer.Ordinal);
        foreach (var prop in props.EnumerateObject())
        {
            if (seen.Add(prop.Name))
            {
                properties.Add((prop.Name, prop.Value));
            }
        }
    }

    private string? ResolveBase(string? refName)
    {
        if (refName is null)
        {
            return null;
        }

        var defName = refName.Split('/').Last();
        if (defName is "JsonPatchDocument" or "JsonPatchOperation")
        {
            return null;
        }

        return _types.ClassNames.TryGetValue(defName, out var name) ? _types.Qualify(name) : null;
    }

    private bool IsDictionaryClass(JsonElement schema, out string valueType)
    {
        valueType = "object";
        if (schema.TryGetProperty("properties", out var props) && props.ValueKind == JsonValueKind.Object &&
            props.EnumerateObject().Any())
        {
            return false;
        }

        if (schema.TryGetProperty("allOf", out _))
        {
            return false;
        }

        if (schema.TryGetProperty("additionalProperties", out var ap) && ap.ValueKind == JsonValueKind.Object)
        {
            valueType = _types.MapType(ap);
            return true;
        }

        return false;
    }

    private static string? GetDescription(JsonElement schema) =>
        schema.TryGetProperty("description", out var d) ? d.GetString() : null;

    private static string Escape(string text) => text.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
