using Azure.DevOps.Sdk.Generator;

// Resolve input/output directories (overridable via args).
var specsDir = args.Length > 0 ? args[0] : Path.Combine(Directory.GetCurrentDirectory(), "specs", "7.2");
var outputDir = args.Length > 1 ? args[1] : Path.Combine(Directory.GetCurrentDirectory(), "src", "Azure.DevOps.Sdk", "Generated");

specsDir = Path.GetFullPath(specsDir);
outputDir = Path.GetFullPath(outputDir);

if (!Directory.Exists(specsDir))
{
    Console.Error.WriteLine($"Specs directory not found: {specsDir}");
    return 1;
}

Console.WriteLine($"Specs:  {specsDir}");
Console.WriteLine($"Output: {outputDir}");

// Clean and recreate the output directory (with a small retry to tolerate Windows
// file-handle races between delete and recreate).
for (var attempt = 0; Directory.Exists(outputDir) && attempt < 5; attempt++)
{
    try
    {
        Directory.Delete(outputDir, recursive: true);
    }
    catch (IOException)
    {
        Thread.Sleep(200);
    }
    catch (UnauthorizedAccessException)
    {
        Thread.Sleep(200);
    }
}

var modelsDir = Path.Combine(outputDir, "Models");
var buildersDir = Path.Combine(outputDir, "Builders");
Directory.CreateDirectory(modelsDir);
Directory.CreateDirectory(buildersDir);

var loader = new SpecLoader();
var areas = loader.Load(specsDir);

var clientWriter = new CodeWriter();
clientWriter.Line("// <auto-generated />");
clientWriter.Line("#nullable enable");
clientWriter.Line();
clientWriter.Open("namespace Azure.DevOps.Sdk");
clientWriter.Open("public sealed partial class AzureDevOpsClient");

var totalClasses = 0;
var totalEnums = 0;
var totalOps = 0;

foreach (var area in areas)
{
    var types = TypeContext.Build(area);

    var models = new ModelEmitter(area, types).Emit();
    File.WriteAllText(Path.Combine(modelsDir, $"{area.AreaName}.Models.cs"), models);

    var builders = new BuilderEmitter(area, types).Emit();
    File.WriteAllText(Path.Combine(buildersDir, $"{area.AreaName}.Builders.cs"), builders.Code);

    clientWriter.Doc($"Operations for the Azure DevOps <c>{area.AreaName}</c> area.");
    clientWriter.Line(
        $"public global::Azure.DevOps.Sdk.{area.AreaName}.{builders.RootBuilderClass} {area.AreaName} " +
        $"=> new global::Azure.DevOps.Sdk.{area.AreaName}.{builders.RootBuilderClass}(_adapter, _pathParameters);");
    clientWriter.Line();

    totalClasses += types.ClassNames.Count;
    totalEnums += types.Enums.Count;
    totalOps += area.Operations.Count;

    Console.WriteLine($"  {area.AreaName,-28} classes={types.ClassNames.Count,-4} enums={types.Enums.Count,-4} ops={area.Operations.Count}");
}

clientWriter.Close();
clientWriter.Close();
File.WriteAllText(Path.Combine(outputDir, "AzureDevOpsClient.Areas.cs"), clientWriter.ToString());

Console.WriteLine();
Console.WriteLine($"Areas: {areas.Count}  Classes: {totalClasses}  Enums: {totalEnums}  Operations: {totalOps}");
return 0;
